plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - Contributors.md
  - README.md
  - Research.md
  - styleguide.md
  - logos.md

theme: jekyll-theme-minimal